#!/usr/bin/env python3
"""Create the fixed LEVIR-Ship split used by reference implementation.

The reference pipeline sorts all 3,896 matching crop stems, shuffles them with
``random.Random(split_seed)`` and slices 2,320/788/788 crops for train/val/test.
This script intentionally reproduces that exact algorithm.  The split seed is
independent of the training seeds: all model runs must share one data split.
"""
from __future__ import annotations

import argparse
import json
import random
import shutil
from pathlib import Path

SPLIT_COUNTS = {"train": 2320, "val": 788, "test": 788}
TOTAL_IMAGES = sum(SPLIT_COUNTS.values())


def _source_dirs(data_root: Path) -> tuple[Path, Path]:
    """Accept either the extracted archive root or LevirShipData itself."""
    dataset = data_root / "LevirShipData"
    if not dataset.is_dir():
        dataset = data_root
    return dataset / "All Images", dataset / "All Annotations"


def _place(src: Path, dst: Path, symlink: bool) -> None:
    if symlink:
        dst.symlink_to(src.resolve())
    else:
        shutil.copy2(src, dst)


def build(
    data_root: Path,
    out_root: Path,
    split_seed: int = 42,
    symlink: bool = True,
) -> dict[str, int]:
    images_src, labels_src = _source_dirs(data_root)
    if not images_src.is_dir():
        raise FileNotFoundError(images_src)
    if not labels_src.is_dir():
        raise FileNotFoundError(labels_src)

    image_stems = {path.stem for path in images_src.glob("*.png")}
    label_stems = {path.stem for path in labels_src.glob("*.txt")}
    if len(image_stems) != TOTAL_IMAGES or image_stems != label_stems:
        raise ValueError(
            f"Expected {TOTAL_IMAGES:,} matching PNG images and TXT labels; "
            f"found {len(image_stems):,} images and {len(label_stems):,} labels"
        )

    # Keep these three lines identical in meaning to create_fixed_split() in
    # reference implementation/train_all_levir_yolov8n_p2_routing.py.
    stems = sorted(image_stems)
    random.Random(split_seed).shuffle(stems)

    # Only replace folders generated by this script.  This also prevents stale
    # links from an older scene-based split from leaking into the new split.
    for generated in (out_root / "images", out_root / "labels"):
        if generated.exists():
            shutil.rmtree(generated)

    counts: dict[str, int] = {}
    manifest: dict[str, object] = {
        "algorithm": "sorted stems + random.Random(split_seed).shuffle + sequential slices",
        "split_seed": split_seed,
        "counts": SPLIT_COUNTS,
        "splits": {},
    }
    start = 0
    for split, count in SPLIT_COUNTS.items():
        selected = stems[start : start + count]
        start += count
        img_out = out_root / "images" / split
        lbl_out = out_root / "labels" / split
        img_out.mkdir(parents=True, exist_ok=True)
        lbl_out.mkdir(parents=True, exist_ok=True)
        for stem in selected:
            _place(images_src / f"{stem}.png", img_out / f"{stem}.png", symlink)
            _place(labels_src / f"{stem}.txt", lbl_out / f"{stem}.txt", symlink)
        counts[split] = len(selected)
        manifest["splits"][split] = selected  # type: ignore[index]

    out_root.mkdir(parents=True, exist_ok=True)
    (out_root / "split_manifest.json").write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8"
    )
    return counts


def write_data_yaml(out_root: Path) -> Path:
    yaml_path = out_root / "data.yaml"
    yaml_path.write_text(
        f"path: {out_root.resolve()}\n"
        "train: images/train\n"
        "val: images/val\n"
        "test: images/test\n"
        "names:\n"
        "  0: ship\n",
        encoding="utf-8",
    )
    return yaml_path


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--data-root", type=Path, required=True,
        help="archive root containing LevirShipData/, or LevirShipData itself",
    )
    parser.add_argument("--out-root", type=Path, required=True)
    parser.add_argument(
        "--split-seed", type=int, default=42,
        help="fixed data-split seed; keep 42 to match reference implementation",
    )
    parser.add_argument(
        "--copy", action="store_true",
        help="copy files instead of symlinking (symlink is faster and saves disk)",
    )
    args = parser.parse_args()
    counts = build(
        args.data_root.resolve(), args.out_root.resolve(),
        split_seed=args.split_seed, symlink=not args.copy,
    )
    yaml_path = write_data_yaml(args.out_root.resolve())
    for split, count in counts.items():
        print(f"{split}: {count} images")
    print(f"split seed: {args.split_seed}")
    print("manifest:", args.out_root.resolve() / "split_manifest.json")
    print("data.yaml:", yaml_path)


if __name__ == "__main__":
    main()
