# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license
"""
Ultralytics neural network modules.

This module provides access to various neural network components used in Ultralytics models, including convolution
blocks, attention mechanisms, transformer components, and detection/segmentation heads.

Examples:
    Visualize a module with Netron
    >>> from ultralytics.nn.modules import Conv
    >>> import torch
    >>> import subprocess
    >>> x = torch.ones(1, 128, 40, 40)
    >>> m = Conv(128, 128)
    >>> f = f"{m._get_name()}.onnx"
    >>> torch.onnx.export(m, x, f)
    >>> subprocess.run(f"onnxslim {f} {f} && open {f}", shell=True, check=True)  # pip install onnxslim
"""

from .block import (
    C1,
    C2,
    C2PSA,
    C3,
    C3TR,
    CIB,
    DFL,
    ELAN1,
    PSA,
    SPP,
    SPPELAN,
    SPPF,
    A2C2f,
    AConv,
    ADown,
    AdversarialPerturbationInjection,
    ASFAttention,
    Attention,
    BiLevelRoutingAttention,
    BNContrastiveHead,
    BoundaryFeatureBlock,
    ConflictFineReconstruction,
    DBSS,
    DualIrreducibilityHIT,
    Bottleneck,
    BottleneckCSP,
    C2f,
    C2fCBAM,
    C2fAttn,
    C2fCIB,
    C2fKV,
    C2fNAT,
    C2fPSA,
    EnSimAM,
    EnSimAMEdgeRepC2f,
    FeatureDGFE,
    GCTS,
    C3CBAM,
    C3Ghost,
    C3k2,
    C3x,
    CBFuse,
    CBLinear,
    ContrastiveHead,
    GhostBottleneck,
    HGBlock,
    HGStem,
    ImagePoolingAttn,
    FullSelfAttention,
    GlobalChannelContextCalibration,
    KVCompressedAttention,
    PatchKVCompressedAttention,
    KVCompressedAttentionPartial,
    KVCompressedTransformerEncoder,
    ChannelKVCompressedAttention,
    M3NATFuse,
    NATBlock,
    MaxSigmoidAttnBlock,
    P1FusionLocalDetail,
    P1GER,
    P1PlainFusion,
    P1DRR,
    Proto,
    RegionRoutingAttentionLite,
    RepC3,
    RepC2f,
    PoolingEdgeRepC2f,
    RepNCSPELAN4,
    RepVGGDW,
    ResNetLayer,
    SCDown,
    ScalSeq,
    TorchVision,
    TopKAdaptiveGroupKVAttention,
    TopKGlobalGroupKVAttention,
    WeightedAdd,
    clear_boundary_context,
    set_boundary_context,
    set_boundary_enabled,
)
from .local_detail import LocalDetailRepC2f
from .carafe import CARAFE, P2GuidedCARAFE
from .p2_guided_ops import (
    P2GuidedDeformConv,
    P2GuidedDynamicConv,
    P2GuidedGatedModulation,
    P2GuidedLocalCrossAttention,
)
from .saturation_fusion import (
    DualGateP2P3Residual, FilteredP2GuidedP3Residual,
    RegularizedSaturationF2Fusion, SaturationFeatureFilter, SaturationGuidedP3F2Residual,
    SaturationGuidedP3Residual, SaturationP2Cue, SaturationP2Residual, SaturationStemF2Residual,
)
from .srm_f2_guidance import SRMF2Guidance
from .conv import (
    CBAM,
    ChannelAttention,
    Concat,
    Conv,
    Conv2,
    ConvTranspose,
    DWConv,
    DWConvTranspose2d,
    Focus,
    GhostConv,
    Index,
    LightConv,
    RepConv,
    SpatialAttention,
    SPDConv,
)
from .asrm import (
    ASRMCandidateSparseRefine, ASRMDetailPriorDownsample, ASRMP4SemanticVerifyResidual, ASRMStructuralPrior, AdaptiveSRM, ContextAwareASRMRefine, RGBToHSV, RGBColorAugment,
    InputASRMAttentionGuidedP2, InputASRMAuxiliaryAttention,
    InputGuidedContextRefine, InputGuidedP2P3ContextRefine, InputGuidedP34ContextRefine, P2ASRMFusion, SPGFusion,
)
from .head import (
    OBB,
    OBB26,
    Classify,
    Detect,
    SRMClsDetect,
    DetectClsAttention,
    HVDecoupledDetect,
    HVDecoupledRegression,
    P2NUDFLDetect,
    P3NUDFLDetect,
    LRPCHead,
    Pose,
    Pose26,
    RTDETRDecoder,
    Segment,
    Segment26,
    SemanticSegment,
    WorldDetect,
    YOLOEDetect,
    YOLOESegment,
    YOLOESegment26,
    v10Detect,
    v10GCTSDetect,
    v10GCTSP3NUDFLDetect,
    v10P3NUDFLDetect,
)
from .transformer import (
    AIFI,
    MLP,
    DeformableTransformerDecoder,
    DeformableTransformerDecoderLayer,
    LayerNorm2d,
    MLPBlock,
    MSDeformAttn,
    TransformerBlock,
    TransformerEncoderLayer,
    TransformerLayer,
)

__all__ = (
    "AIFI",
    "C1",
    "C2",
    "C2PSA",
    "C3",
    "C3TR",
    "CBAM",
    "CIB",
    "DFL",
    "DBSS",
    "DualIrreducibilityHIT",
    "GCTS",
    "ELAN1",
    "MLP",
    "OBB",
    "OBB26",
    "PSA",
    "SPP",
    "SPPELAN",
    "SPPF",
    "A2C2f",
    "AConv",
    "ADown",
    "ASRMCandidateSparseRefine",
    "AdaptiveSRM",
    "RGBToHSV",
    "RGBColorAugment",
    "AdversarialPerturbationInjection",
    "ASFAttention",
    "Attention",
    "BiLevelRoutingAttention",
    "BNContrastiveHead",
    "BoundaryFeatureBlock",
    "ConflictFineReconstruction",
    "Bottleneck",
    "BottleneckCSP",
    "C2f",
    "C2fCBAM",
    "C2fAttn",
    "C2fCIB",
    "C2fKV",
    "C2fNAT",
    "C2fPSA",
    "EnSimAM",
    "EnSimAMEdgeRepC2f",
    "FeatureDGFE",
    "C3CBAM",
    "C3Ghost",
    "C3k2",
    "C3x",
    "CBFuse",
    "CBLinear",
    "CARAFE",
    "P2GuidedCARAFE",
    "ChannelAttention",
    "Classify",
    "Concat",
    "ContextAwareASRMRefine",
    "ContrastiveHead",
    "Conv",
    "Conv2",
    "ConvTranspose",
    "DWConv",
    "DWConvTranspose2d",
    "DeformableTransformerDecoder",
    "DeformableTransformerDecoderLayer",
    "Detect",
    "SRMClsDetect",
    "HVDecoupledDetect",
    "HVDecoupledRegression",
    "Focus",
    "GhostBottleneck",
    "GhostConv",
    "HGBlock",
    "HGStem",
    "ImagePoolingAttn",
    "Index",
    "InputASRMAttentionGuidedP2",
    "InputASRMAuxiliaryAttention",
    "ASRMStructuralPrior",
    "SPGFusion",
    "SRMF2Guidance",
    "ASRMDetailPriorDownsample",
    "ASRMP4SemanticVerifyResidual",
    "InputGuidedContextRefine",
    "InputGuidedP2P3ContextRefine",
    "InputGuidedP34ContextRefine",
    "FullSelfAttention",
    "GlobalChannelContextCalibration",
    "KVCompressedAttention",
    "PatchKVCompressedAttention",
    "KVCompressedAttentionPartial",
    "KVCompressedTransformerEncoder",
    "ChannelKVCompressedAttention",
    "LRPCHead",
    "LayerNorm2d",
    "LightConv",
    "LocalDetailRepC2f",
    "P1FusionLocalDetail",
    "P1GER",
    "P1PlainFusion",
    "P1DRR",
    "M3NATFuse",
    "NATBlock",
    "MLPBlock",
    "MSDeformAttn",
    "MaxSigmoidAttnBlock",
    "P2ASRMFusion",
    "P2GuidedDeformConv",
    "P2GuidedDynamicConv",
    "P2GuidedGatedModulation",
    "P2GuidedLocalCrossAttention",
    "SaturationP2Residual",
    "SaturationP2Cue",
    "SaturationGuidedP3Residual",
    "SaturationFeatureFilter",
    "FilteredP2GuidedP3Residual",
    "DualGateP2P3Residual",
    "SaturationStemF2Residual",
    "SaturationGuidedP3F2Residual",
    "RegularizedSaturationF2Fusion",
    "Pose",
    "Pose26",
    "P2NUDFLDetect",
    "P3NUDFLDetect",
    "Proto",
    "RegionRoutingAttentionLite",
    "RTDETRDecoder",
    "RepC3",
    "RepC2f",
    "PoolingEdgeRepC2f",
    "RepConv",
    "RepNCSPELAN4",
    "RepVGGDW",
    "ResNetLayer",
    "SCDown",
    "ScalSeq",
    "Segment",
    "Segment26",
    "SemanticSegment",
    "SpatialAttention",
    "SPDConv",
    "TorchVision",
    "TopKAdaptiveGroupKVAttention",
    "TopKGlobalGroupKVAttention",
    "TransformerBlock",
    "TransformerEncoderLayer",
    "TransformerLayer",
    "WorldDetect",
    "YOLOEDetect",
    "YOLOESegment",
    "YOLOESegment26",
    "WeightedAdd",
    "clear_boundary_context",
    "set_boundary_context",
    "set_boundary_enabled",
    "v10Detect",
    "v10GCTSDetect",
    "v10GCTSP3NUDFLDetect",
    "v10P3NUDFLDetect",
)
